### ISSUE TITLE
Data Source

### ISSUE THREAD

**Issue by jcuenod** [eliranwong/MP3_OpenHebrewGreekBible#1]
Where did this data come from? The attribution in the license is this repository but it's unclear whether it was originally sourced from somewhere else and modified for use in Unique Bible App. Is it machine generated or are these original recordings by some or many volunteers paid or unpaid? It's valuable to know this information when considering using this data.

**Comment by eliranwong** [comment]
Hi James, please read sources at:

https://github.com/eliranwong/MP3_OpenHebrewGreekBible_fast#about-ohgb

Audio files are machine generated.

**Comment by eliranwong** [comment]
You may find more details about sources at:

Open Hebrew Bible project:

https://github.com/eliranwong/OpenHebrewBible

Open Greek New Testament project:

https://github.com/eliranwong/OpenGNT

**Comment by jcuenod** [comment]
> Audio files are machine generated.

What software did you use?

> You may find more details about sources at: ...

Those references led me to this repository when I was initially looking for more information.

**Comment by eliranwong** [comment]
> What software did you use?

As described in Readme, I use UniqueBibleApp

https://github.com/eliranwong/UniqueBible

It is an open source project that you may check the python scripts. 

I have a specific plugin to use Google cloud tts service with UniqueBibleApp plugin:

https://github.com/eliranwong/UniqueBible_Plugins_Menu/blob/main/developer_Create%20Audio%20Bible.py.zip
